// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMess: typeof import('element-plus/es')['ElMess']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
export {}
