// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheck: typeof import('element-plus/es')['ElCheck']
    ElCheckb: typeof import('element-plus/es')['ElCheckb']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadi: typeof import('element-plus/es')['ElRadi']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GlobalFooter: typeof import('./src/components/layout/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./src/components/layout/GlobalHeader.vue')['default']
    ImageUpdater: typeof import('./src/components/image/ImageUpdater.vue')['default']
    ListItem: typeof import('./src/components/music/ListItem.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    MusicList: typeof import('./src/components/music/MusicList.vue')['default']
    ProgressBar: typeof import('./src/components/music/ProgressBar.vue')['default']
    QrLoginPage: typeof import('./src/components/login/QrLoginPage.vue')['default']
    RcmdListItem: typeof import('./src/components/playlist/RcmdListItem.vue')['default']
    RegionSelect: typeof import('./src/components/form/RegionSelect.vue')['default']
    RegisterForm: typeof import('./src/components/register/RegisterForm.vue')['default']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
  }
}

export { }
